"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-sto)!_80d0e_a9)pq(y#*69k6k0ndb8)i^x8z)hk_(xpr@vt4f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']  # В Docker разрешаем все хосты

# Настройки для работы за прокси (Nginx)
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF настройки для работы за прокси
# Можно переопределить через переменную окружения CSRF_TRUSTED_ORIGINS (через запятую)
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',')]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://getsparks.ru',
        'http://getsparks.ru',
        'https://www.getsparks.ru',
        'http://www.getsparks.ru',
        'https://149.154.66.216',
        'http://149.154.66.216',
    ]

# Настройки cookies
# В production (DEBUG=False) используем Secure cookies только если действительно HTTPS
# В DEBUG режиме разрешаем HTTP для разработки
# Можно принудительно включить через переменную окружения FORCE_HTTPS=true
FORCE_HTTPS = os.environ.get('FORCE_HTTPS', 'false').lower() == 'true'
# В DEBUG режиме не используем Secure cookies (для локальной разработки)
# В production используем Secure cookies только если FORCE_HTTPS=True или если действительно HTTPS
USE_SECURE_COOKIES = FORCE_HTTPS or (not DEBUG and not FORCE_HTTPS)

SESSION_COOKIE_SECURE = False  # Отключаем Secure для работы через HTTP/HTTPS прокси
CSRF_COOKIE_SECURE = False      # Отключаем Secure для работы через HTTP/HTTPS прокси
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'apps.admin_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Логирование CSRF ошибок для отладки (включаем всегда для диагностики)
import logging
logger = logging.getLogger('django.security.csrf')
logger.setLevel(logging.DEBUG)

# Настройка логирования для вывода в консоль (Docker logs)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.admin_app': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Используем тот же SQLite файл что и Backend
# В Docker используем путь из переменной окружения, иначе относительный путь
DATABASE_PATH_ENV = os.environ.get('DATABASE_PATH')
if DATABASE_PATH_ENV:
    DATABASE_PATH = Path(DATABASE_PATH_ENV).resolve()
else:
    # Путь к БД в backend/ директории (общая для админки и бэкенда)
    # BASE_DIR = admin/ (так как settings.py в admin/config/, и parent.parent = admin/)
    # BASE_DIR.parent = корень проекта
    # backend/sparks.db относительно корня проекта
    db_path = BASE_DIR.parent / 'backend' / 'sparks.db'
    # Преобразуем в абсолютный путь
    DATABASE_PATH = db_path.resolve()
    # Создаем директорию если нужно
    DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Логируем путь для отладки
    import logging
    logger = logging.getLogger(__name__)
    logger.info(f"Database path: {DATABASE_PATH}")
    logger.info(f"Database exists: {DATABASE_PATH.exists()}")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(DATABASE_PATH),
    }
}

# Отключаем авто-миграции только для admin_app (таблицы управляются через Alembic)
# Системные приложения Django (auth, sessions, contenttypes, admin) используют свои миграции
MIGRATION_MODULES = {
    'admin_app': None,  # Таблицы admin_app управляются через Alembic в бэкенде
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# URL для статики
STATIC_URL = '/static/'

# Каталог, куда collectstatic будет собирать файлы статики внутри контейнера
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Если появятся свои статические файлы админки, их можно будет добавить так:
# STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
