"""Initial migration

Revision ID: 421742cc02d9
Revises: 
Create Date: 2025-12-07 23:42:57.862002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Определяем тип БД для правильной настройки
def get_database_type():
    """Определяет тип базы данных"""
    bind = op.get_bind()
    return bind.dialect.name


# revision identifiers, used by Alembic.
revision: str = '421742cc02d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Определяем тип БД
    db_type = get_database_type()
    is_sqlite = db_type == 'sqlite'
    
    # Настройки для DateTime в зависимости от БД
    datetime_type = sa.DateTime() if is_sqlite else sa.DateTime(timezone=True)
    datetime_default = sa.text('CURRENT_TIMESTAMP') if is_sqlite else sa.text('now()')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_index(op.f('ix_task_categories_slug'), 'task_categories', ['slug'], unique=True)
    op.create_table('category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_id', name='uq_category_translation')
    )
    op.create_index(op.f('ix_category_translations_id'), 'category_translations', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'COUPLE', name='gender'), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.Column('updated_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('completed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_completed_task')
    )
    op.create_index(op.f('ix_completed_tasks_id'), 'completed_tasks', ['id'], unique=False)
    op.create_table('daily_free_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_reset', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_free_task')
    )
    op.create_index(op.f('ix_daily_free_tasks_id'), 'daily_free_tasks', ['id'], unique=False)
    op.create_table('task_gender_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'COUPLE', 'ALL', name='gendertarget'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'gender', name='uq_task_gender_target')
    )
    op.create_index(op.f('ix_task_gender_targets_id'), 'task_gender_targets', ['id'], unique=False)
    op.create_table('task_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'language_id', name='uq_task_translation')
    )
    op.create_index(op.f('ix_task_translations_id'), 'task_translations', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'TASK_PAYMENT', 'BONUS', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('payment_method', sa.Enum('YOOKASSA', 'DAILY_BONUS', 'SYSTEM', name='paymentmethod'), nullable=True),
    sa.Column('yookassa_payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_yookassa_payment_id'), 'transactions', ['yookassa_payment_id'], unique=False)
    op.create_table('user_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category')
    )
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_transactions_yookassa_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_task_translations_id'), table_name='task_translations')
    op.drop_table('task_translations')
    op.drop_index(op.f('ix_task_gender_targets_id'), table_name='task_gender_targets')
    op.drop_table('task_gender_targets')
    op.drop_index(op.f('ix_daily_free_tasks_id'), table_name='daily_free_tasks')
    op.drop_table('daily_free_tasks')
    op.drop_index(op.f('ix_completed_tasks_id'), table_name='completed_tasks')
    op.drop_table('completed_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_category_translations_id'), table_name='category_translations')
    op.drop_table('category_translations')
    op.drop_index(op.f('ix_task_categories_slug'), table_name='task_categories')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_table('task_categories')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
