"""add_daily_bonus_table

Revision ID: b1b7946a6c3b
Revises: 421742cc02d9
Create Date: 2025-12-09 17:39:25.388996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Определяем тип БД для правильной настройки
def get_database_type():
    """Определяет тип базы данных"""
    bind = op.get_bind()
    return bind.dialect.name


# revision identifiers, used by Alembic.
revision: str = 'b1b7946a6c3b'
down_revision: Union[str, None] = '421742cc02d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Определяем тип БД
    db_type = get_database_type()
    is_sqlite = db_type == 'sqlite'
    
    # Настройки для DateTime в зависимости от БД
    datetime_type = sa.DateTime() if is_sqlite else sa.DateTime(timezone=True)
    datetime_default = sa.text('CURRENT_TIMESTAMP') if is_sqlite else sa.text('now()')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('bonus_amount', sa.Integer(), nullable=False),
    sa.Column('claimed_at', datetime_type, server_default=datetime_default, nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_bonus')
    )
    op.create_index(op.f('ix_daily_bonuses_id'), 'daily_bonuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_bonuses_id'), table_name='daily_bonuses')
    op.drop_table('daily_bonuses')
    # ### end Alembic commands ###
