# Generated by Django 4.2.26 on 2025-12-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория заданий',
                'verbose_name_plural': 'Категории заданий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('couple', 'Пара')], max_length=10, verbose_name='Тип аккаунта')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Супер администратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_daily_bonus', models.DateField(blank=True, null=True, verbose_name='Последний ежедневный бонус')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Покупка'), ('bonus', 'Бонус'), ('task_payment', 'Оплата задания'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип транзакции')),
                ('payment_method', models.CharField(blank=True, choices=[('yookassa', 'ЮKassa'), ('daily_bonus', 'Ежедневный бонус'), ('system', 'Система')], max_length=20, null=True, verbose_name='Способ оплаты')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершена'), ('failed', 'Неудачна'), ('refunded', 'Возвращена')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='admin_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='admin_app.taskcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория заданий',
                'verbose_name_plural': 'Подкатегории заданий',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(blank=True, related_name='task_categories', to='admin_app.taskcategory', verbose_name='Категории для фильтрации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_app.taskcategory', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='admin_app.tasksubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskGenderTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_target', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('couple', 'Пара'), ('all', 'Все')], max_length=10, verbose_name='Для кого')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_targets', to='admin_app.task')),
            ],
            options={
                'verbose_name': 'Целевая аудитория задания',
                'verbose_name_plural': 'Целевые аудитории заданий',
                'unique_together': {('task', 'gender_target')},
            },
        ),
        migrations.CreateModel(
            name='DailyUserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатное')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_user_tasks', to='admin_app.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='admin_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ежедневное задание пользователя',
                'verbose_name_plural': 'Ежедневные задания пользователей',
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'task', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='admin_app.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='admin_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
